/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Ferramenta;
import Model.Emprestimo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class GerenciarFerramentas extends javax.swing.JFrame {
    
    private Ferramenta objetoFerramenta;
    private Emprestimo objetoEmprestimo;
    /**
     * Creates new form GerenciarFerramentas
     */
    public GerenciarFerramentas() {
        initComponents();
        TelaPrincipal.CarregarIcone(this);
        this.objetoFerramenta = new Ferramenta();
        this.objetoEmprestimo = new Emprestimo();
        this.carregarTabela();
        this.carregarTotal();
        this.jTableGerenciarFerramentas.setAutoCreateRowSorter(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGerenciarFerramentas = new javax.swing.JTable();
        textNome1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCusto = new javax.swing.JTextField();
        b_cancelar1 = new javax.swing.JButton();
        b_alterar1 = new javax.swing.JButton();
        b_apagar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextTotalGasto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToolShare");

        jTableGerenciarFerramentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Disponibilidade", "Custo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGerenciarFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGerenciarFerramentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGerenciarFerramentas);
        if (jTableGerenciarFerramentas.getColumnModel().getColumnCount() > 0) {
            jTableGerenciarFerramentas.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        textNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNome1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Marca:");

        jLabel5.setText("Custo:");

        b_cancelar1.setText("Cancelar");
        b_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelar1ActionPerformed(evt);
            }
        });

        b_alterar1.setText("Alterar");
        b_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterar1ActionPerformed(evt);
            }
        });

        b_apagar1.setText("Apagar");
        b_apagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagar1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome:");

        jLabel1.setText("Total gasto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_cancelar1)
                        .addGap(18, 18, 18)
                        .addComponent(b_alterar1)
                        .addGap(18, 18, 18)
                        .addComponent(b_apagar1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextTotalGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTotalGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar1)
                    .addComponent(b_alterar1)
                    .addComponent(b_apagar1))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(725, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNome1ActionPerformed

    private void b_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelar1ActionPerformed

    private void b_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterar1ActionPerformed
        // TODO add your handling code here:
        int id = 0;
        String nome = "";
        String marca = "";
        double custo = 0;
        
        try{
            
            if (this.jTableGerenciarFerramentas.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione uma ferramenta para alterar");
            } else {
                id = Integer.parseInt(this.jTableGerenciarFerramentas.getValueAt(this.jTableGerenciarFerramentas.getSelectedRow(), 0).toString());
            }             
            

            if (this.textNome1.getText().length() < 2) {
                throw new Mensagens ("Nome muito curto");
            } else {
                nome = this.textNome1.getText();
            }

            for (char c : nome.toCharArray())
            {
                if (Character.isDigit(c))
                {
                    throw new Mensagens("Nome deve conter apenas letras");
                }
            }

            if (this.textCusto.getText().length() < 0) {       
                throw new Mensagens("Custo deve conter ao menos 3 caracteres.");
            }          
            else {
                custo = Double.parseDouble(this.textCusto.getText());
            }

            if (this.textMarca.getText().length() < 2) {
                throw new Mensagens("Marca muito curta");
            }
            else {
                marca = this.textMarca.getText();
            }
            
            System.out.println(id + nome + marca + custo);
            
            if (this.objetoFerramenta.UpdateFerramentaBD(id, nome, marca, custo)) {
                this.textNome1.setText(""); 
                this.textMarca.setText(""); 
                this.textCusto.setText("");
                JOptionPane.showMessageDialog(rootPane, "Ferramenta alterada com sucesso! ");               
            }
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Insira um valor valido: " + ne.getMessage());
        } finally {
            carregarTabela();
        }   
    }//GEN-LAST:event_b_alterar1ActionPerformed

    private void b_apagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagar1ActionPerformed
        // TODO add your handling code here:
        try {
            int id = 0;
            
            if (this.jTableGerenciarFerramentas.getSelectedRow() == -1) {
                throw new Mensagens("Selecione uma ferramenta para apagar");
            } else {
                id = Integer.parseInt(this.jTableGerenciarFerramentas.getValueAt(this.jTableGerenciarFerramentas.getSelectedRow(), 0).toString());
            }
            
            //int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar essa ferramenta? ");
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja apagar essa ferramenta?", "Selecione uma opção", WIDTH);
            
            if (resposta == 0) {
                if (this.objetoEmprestimo.setFerramentaIdToNull(id) && this.objetoFerramenta.DeleteFerramentaoBD(id)) {
                    this.textMarca.setText("");
                    this.textNome1.setText("");
                    this.textCusto.setText("");
                    
                    JOptionPane.showMessageDialog(rootPane, "Ferramenta apagada com sucesso!");
                }
            }
                
        } catch(Mensagens e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } finally {
            carregarTabela();
        }
    }//GEN-LAST:event_b_apagar1ActionPerformed

    private void jTableGerenciarFerramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGerenciarFerramentasMouseClicked
        // TODO add your handling code here:
        if (this.jTableGerenciarFerramentas.getSelectedRow() != -1) {

            String nome = this.jTableGerenciarFerramentas.getValueAt(this.jTableGerenciarFerramentas.getSelectedRow(), 1).toString();
            String marca = this.jTableGerenciarFerramentas.getValueAt(this.jTableGerenciarFerramentas.getSelectedRow(), 2).toString();
            String custo = this.jTableGerenciarFerramentas.getValueAt(this.jTableGerenciarFerramentas.getSelectedRow(), 4).toString();
            

            this.textNome1.setText(nome);
            this.textMarca.setText(marca);
            this.textCusto.setText(custo);
            
            
        }        
    }//GEN-LAST:event_jTableGerenciarFerramentasMouseClicked
   
    @SuppressWarnings("unchecked")
    public void carregarTabela() {
        
        DefaultTableModel model = (DefaultTableModel) this.jTableGerenciarFerramentas.getModel();
        model.setNumRows(0);
        
        ArrayList<Ferramenta> lista = new ArrayList<>();
        
        lista = objetoFerramenta.getMinhaLista();
           
        for (Ferramenta ferramenta : lista) {
            model.addRow(new Object[]{
                ferramenta.getId(),
                ferramenta.getNome(),
                ferramenta.getMarca(),
                ferramenta.getDisponibilidade(),
                ferramenta.getCusto(),

            });
        } 
    }
    
    public void carregarTotal() {
        double total = 0;
        total = this.objetoFerramenta.calcularTotal();
        
        this.jTextTotalGasto.setText("R$ " + Double.toString(total));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar1;
    private javax.swing.JButton b_apagar1;
    private javax.swing.JButton b_cancelar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGerenciarFerramentas;
    private javax.swing.JTextField jTextTotalGasto;
    private javax.swing.JTextField textCusto;
    private javax.swing.JTextField textMarca;
    private javax.swing.JTextField textNome1;
    // End of variables declaration//GEN-END:variables
}
