/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Toolkit;
import javax.swing.JFrame;



public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        TelaPrincipal.CarregarIcone(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCard = new javax.swing.JPanel();
        telaPrincipal = new javax.swing.JPanel();
        btnTelaFerramentas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telaAmigos = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        gerenciarAmigosBtn1 = new javax.swing.JButton();
        btnVoltarPrincipal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        telaFerramentas = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btnVoltarPrincipal2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToolShare");
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        setSize(new java.awt.Dimension(625, 360));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanelCard.setForeground(new java.awt.Color(102, 102, 102));
        jPanelCard.setPreferredSize(new java.awt.Dimension(625, 360));
        jPanelCard.setLayout(new java.awt.CardLayout());

        telaPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        telaPrincipal.setLayout(null);

        btnTelaFerramentas.setBackground(new java.awt.Color(204, 204, 204));
        btnTelaFerramentas.setForeground(new java.awt.Color(51, 51, 51));
        btnTelaFerramentas.setText("Ferramentas");
        btnTelaFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaFerramentasActionPerformed(evt);
            }
        });
        telaPrincipal.add(btnTelaFerramentas);
        btnTelaFerramentas.setBounds(324, 160, 196, 56);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Amigos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        telaPrincipal.add(jButton2);
        jButton2.setBounds(122, 160, 196, 56);

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setForeground(new java.awt.Color(51, 51, 51));
        btn3.setText("Realizar Emprestimo");
        btn3.setToolTipText("");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        telaPrincipal.add(btn3);
        btn3.setBounds(120, 100, 404, 54);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bem Vindo!");
        telaPrincipal.add(jLabel1);
        jLabel1.setBounds(270, 60, 124, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/360_F_209198087_8XQcOdJX3OU7EMJZQ2x0iGKM5UmDuCQs.jpg"))); // NOI18N
        telaPrincipal.add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 350);

        jPanelCard.add(telaPrincipal, "card2");

        telaAmigos.setForeground(new java.awt.Color(255, 51, 51));
        telaAmigos.setPreferredSize(new java.awt.Dimension(625, 360));
        telaAmigos.setLayout(null);

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setForeground(new java.awt.Color(51, 51, 51));
        btn1.setText("Cadastrar Amigo");
        btn1.setToolTipText("");
        btn1.setPreferredSize(new java.awt.Dimension(200, 80));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        telaAmigos.add(btn1);
        btn1.setBounds(210, 60, 200, 80);

        gerenciarAmigosBtn1.setBackground(new java.awt.Color(204, 204, 204));
        gerenciarAmigosBtn1.setForeground(new java.awt.Color(51, 51, 51));
        gerenciarAmigosBtn1.setText("Gerenciar Amigos");
        gerenciarAmigosBtn1.setPreferredSize(new java.awt.Dimension(200, 80));
        gerenciarAmigosBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarAmigosBtn1ActionPerformed(evt);
            }
        });
        telaAmigos.add(gerenciarAmigosBtn1);
        gerenciarAmigosBtn1.setBounds(210, 150, 200, 80);

        btnVoltarPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        btnVoltarPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        btnVoltarPrincipal.setText("Voltar");
        btnVoltarPrincipal.setPreferredSize(new java.awt.Dimension(100, 35));
        btnVoltarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPrincipalActionPerformed(evt);
            }
        });
        telaAmigos.add(btnVoltarPrincipal);
        btnVoltarPrincipal.setBounds(260, 240, 100, 35);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/360_F_209198087_8XQcOdJX3OU7EMJZQ2x0iGKM5UmDuCQs.jpg"))); // NOI18N
        telaAmigos.add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 350);

        jPanelCard.add(telaAmigos, "card3");

        telaFerramentas.setPreferredSize(new java.awt.Dimension(625, 360));
        telaFerramentas.setLayout(null);

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setForeground(new java.awt.Color(51, 51, 51));
        btn2.setText("Cadastrar Ferramenta");
        btn2.setToolTipText("");
        btn2.setMaximumSize(new java.awt.Dimension(500, 500));
        btn2.setPreferredSize(new java.awt.Dimension(200, 80));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        telaFerramentas.add(btn2);
        btn2.setBounds(210, 60, 200, 80);

        btnVoltarPrincipal2.setBackground(new java.awt.Color(204, 204, 204));
        btnVoltarPrincipal2.setForeground(new java.awt.Color(51, 51, 51));
        btnVoltarPrincipal2.setText("Voltar");
        btnVoltarPrincipal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPrincipal2ActionPerformed(evt);
            }
        });
        telaFerramentas.add(btnVoltarPrincipal2);
        btnVoltarPrincipal2.setBounds(260, 240, 100, 35);

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setForeground(new java.awt.Color(51, 51, 51));
        btn4.setText("Gerenciar Ferramenta");
        btn4.setToolTipText("");
        btn4.setPreferredSize(new java.awt.Dimension(200, 80));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        telaFerramentas.add(btn4);
        btn4.setBounds(210, 150, 200, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/360_F_209198087_8XQcOdJX3OU7EMJZQ2x0iGKM5UmDuCQs.jpg"))); // NOI18N
        telaFerramentas.add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 350);

        jPanelCard.add(telaFerramentas, "card4");

        getContentPane().add(jPanelCard);
        jPanelCard.setBounds(0, 0, 625, 346);

        jMenuRelatorios.setText("Relatórios");

        jMenuItem1.setText("Relatório de Emprestimos Realizados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem1);

        jMenuItem2.setText("Relatório de Emprestimos Ativos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem2);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(641, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaFerramentasActionPerformed
        // TODO add your handling code here:
        jPanelCard.removeAll();
        jPanelCard.add(telaFerramentas);
        jPanelCard.repaint();
        jPanelCard.revalidate();   
    }//GEN-LAST:event_btnTelaFerramentasActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        EmprestimoFerramenta empFerramenta = new EmprestimoFerramenta();
        empFerramenta.setVisible(true);
    }//GEN-LAST:event_btn3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelCard.removeAll();
        jPanelCard.add(telaAmigos);
        jPanelCard.repaint();
        jPanelCard.revalidate();      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        CadastroAmigos telaCadastroAmigos = new CadastroAmigos();
        telaCadastroAmigos.setVisible(true);

    }//GEN-LAST:event_btn1ActionPerformed

    private void gerenciarAmigosBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarAmigosBtn1ActionPerformed
        // TODO add your handling code here:
        GerenciarAmigos gerenciaAmigos = new GerenciarAmigos();
        gerenciaAmigos.setVisible(true);
    }//GEN-LAST:event_gerenciarAmigosBtn1ActionPerformed

    private void btnVoltarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPrincipalActionPerformed
        // TODO add your handling code here:
        jPanelCard.removeAll();
        jPanelCard.add(telaPrincipal);
        jPanelCard.repaint();
        jPanelCard.revalidate();
    }//GEN-LAST:event_btnVoltarPrincipalActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        CadastroFerramentas cadastroFerr = new CadastroFerramentas();
        cadastroFerr.setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnVoltarPrincipal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPrincipal2ActionPerformed
        // TODO add your handling code here:
        jPanelCard.removeAll();
        jPanelCard.add(telaPrincipal);
        jPanelCard.repaint();
        jPanelCard.revalidate();
    }//GEN-LAST:event_btnVoltarPrincipal2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        RelatorioEmprestimos relatorioEmp = new RelatorioEmprestimos();
        relatorioEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        GerenciarFerramentas gerenciarFerramentas = new GerenciarFerramentas();
        gerenciarFerramentas.setVisible(true);
    }//GEN-LAST:event_btn4ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
            // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        EmprestimosAtivos empAtv = new EmprestimosAtivos();
        empAtv.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    public static void CarregarIcone(JFrame jf) {
        jf.setIconImage(Toolkit.getDefaultToolkit().getImage("src/View/icon_a3.png"));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnTelaFerramentas;
    private javax.swing.JButton btnVoltarPrincipal;
    private javax.swing.JButton btnVoltarPrincipal2;
    private javax.swing.JButton gerenciarAmigosBtn1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel telaAmigos;
    private javax.swing.JPanel telaFerramentas;
    private javax.swing.JPanel telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
